### ISSUE TITLE
problems with Eclipse

### ISSUE THREAD

**Issue by Patrice-H** [Patrice-H/java_tests#2]
![trash](https://github.com/Patrice-H/java_tests/assets/48163300/576dcdeb-ca18-4151-b4d9-c481b0fc2750)

**Comment by Patrice-H** [comment]
The application doesn't run :

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/SpringApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.hello.spring.Application.main(Application.java:10)

**Comment by Patrice-H** [comment]
Fixed by reinstalling but : 

![trash](https://github.com/Patrice-H/java_tests/assets/48163300/dabd76fb-2c49-49e4-8547-e9ca28d9ebed)

**Comment by Patrice-H** [comment]
![trash](https://github.com/Patrice-H/java_tests/assets/48163300/316e63c1-2d43-42d6-85fa-708f7250e5d9)

in VS Code

![trash](https://github.com/Patrice-H/java_tests/assets/48163300/71d91cf8-0955-4815-8add-2932a35ad2ae)

**Comment by Patrice-H** [comment]
Fixes by changing JRE in Package Explorer.

- right click and select Properties

![trash](https://github.com/Patrice-H/java_tests/assets/48163300/dab0da17-bc67-4fcd-835e-db64fbb1ac74)

- choose the right version

![trash](https://github.com/Patrice-H/java_tests/assets/48163300/92c8f332-3212-44ad-8e37-b6fc10612176)

**Comment by Patrice-H** [comment]
Works with JRE (jdk1.8.0_361)

[INFO] Scanning for projects...
Downloading from : https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Progress (1): 2.2/21 kB
Progress (1): 8.2/21 kB
Progress (1): 8.2/21 kB
Progress (2): 8.2/21 kB | 3.0/14 kB
Progress (2): 8.2/21 kB | 8.2/14 kB
Progress (2): 8.2/21 kB | 3.0/14 kB
Progress (2): 2.0/21 kB | 3.0/14 kB
                                   
Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 15 kB/s)
Downloaded from : https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 20 kB/s)
Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-archetype-plugin/maven-metadata.xml
Progress (1): 980 B
                   
Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-archetype-plugin/maven-metadata.xml (980 B at 5.8 kB/s)
```
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> archetype:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< archetype:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- archetype:3.2.1:generate (default-cli) @ standalone-pom ---
[WARNING] Parameter 'localRepository'is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.apache.maven.archetypes:maven-archetype-site:1.4] found in catalog remote
[INFO] Using property: groupId = net.migration-cms
[INFO] Using property: artifactId = essai
[INFO] Using property: version = 0.0.1-SNAPSHOT
[INFO] Using property: package = net.migration_cms.essai
Confirm properties configuration:
groupId: net.migration-cms
artifactId: essai
version: 0.0.1-SNAPSHOT
package: net.migration_cms.essai
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: maven-archetype-site:1.4
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: net.migration-cms
[INFO] Parameter: artifactId, Value: essai
[INFO] Parameter: version, Value: 0.0.1-SNAPSHOT
[INFO] Parameter: package, Value: net.migration_cms.essai
[INFO] Parameter: packageInPathFormat, Value: net/migration_cms/essai
[INFO] Parameter: package, Value: net.migration_cms.essai
[INFO] Parameter: version, Value: 0.0.1-SNAPSHOT
[INFO] Parameter: groupId, Value: net.migration-cms
[INFO] Parameter: artifactId, Value: essai
[INFO] Project created from Archetype in dir: E:\Projets\java\tests\essai
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2023-07-25T14:35:26+02:00
[INFO] ------------------------------------------------------------------------
```
